name: randcomments
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  dio: ^3.0.9
  equatable: ^1.1.0
  flutter_secure_storage: ^3.3.3
  firebase: ^7.3.0
  firebase_database: ^3.1.3
  intl: ^0.16.1
  dartz: ^0.8.9

dev_dependencies:
  build_runner: ^1.0.0
  # To serialize models run: flutter packages pub run build_runner build
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
